os: linux
dist: trusty
sudo: required
services:
  - postgresql

before_install:
  - wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a/swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04.tar.gz 
  - tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04.tar.gz
  - export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04/usr/bin:$PATH
  - sudo apt-get -y install clang-3.8 unixodbc-dev unzip wget tar
  - sudo ln -s /usr/bin/clang-3.8 /usr/bin/clang
  - wget https://github.com/IBM-DTeam/swift-for-db2-cli/archive/master.zip && unzip master.zip && cd swift-for-db2-cli-master && sudo ./cli.sh && . env.sh && cd .. && rm -f master.zip && rm -rf swift-for-db2-cli-master
  - git clone https://github.com/IBM-Swift/todolist-tests Tests

script:
    - swift build
    - swift test