os: linux
dist: trusty
sudo: required

before_install:
  - wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a/swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04.tar.gz 
  - tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04.tar.gz
  - export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-09-07-a-ubuntu14.04/usr/bin:$PATH
  - sudo apt-get -y install clang clang-3.8 unixodbc-dev unzip wget tar
  - wget https://github.com/IBM-DTeam/swift-for-db2-cli/archive/master.zip && unzip master.zip && cd swift-for-db2-cli-master && sudo ./cli.sh && . env.sh && cd .. && rm -f master.zip && rm -rf swift-for-db2-cli-master

script:
    - swift build -Xcc -fblocks -Xlinker -rpath -Xlinker .build/debug