os: linux
dist: trusty
sudo: required

before_install:
  - wget https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz 
  - tar xzvf swift-3.0-RELEASE-ubuntu14.04.tar.gz
  - export PATH=swift-3.0-RELEASE-ubuntu14.04/usr/bin:$PATH
  - sudo apt-get -y install clang-3.8 unixodbc-dev unzip wget tar
  - sudo ln -s /usr/bin/clang-3.8 /usr/bin/clang
  - wget https://github.com/IBM-DTeam/swift-for-db2-cli/archive/master.zip && unzip master.zip && cd swift-for-db2-cli-master && sudo ./cli.sh && . env.sh && cd .. && rm -f master.zip && rm -rf swift-for-db2-cli-master

script:
    - swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib
    - swift test -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib

